spring: 
  jpa: 
    hibernate: 
      ddl-auto: update
  datasource: 
    url: jdbc:postgresql://localhost:5432/NovelVistaTest
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  mvc: 
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp